# Generated by Django 4.1 on 2023-04-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('feedback_date', models.DateField(blank=True, null=True)),
                ('is_opened', models.BooleanField()),
            ],
            options={
                'db_table': 'BookFeedback',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('bookTitle', models.CharField(max_length=30)),
                ('authorName', models.CharField(max_length=75)),
                ('bookThumbnail', models.FileField(blank=True, upload_to='bookthumbnails/')),
                ('gener', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('bookpdf', models.FileField(upload_to='book-pdfs/')),
                ('releaseDate', models.CharField(max_length=20)),
                ('publisher_id', models.IntegerField(blank=True)),
                ('published', models.BooleanField(blank=True, choices=[(True, 'publish'), (False, 'Save Draft')], default=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='bookLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookPublisher.books')),
            ],
        ),
    ]
