# Generated by Django 4.1 on 2023-04-12 11:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('security_question1', models.CharField(choices=[('what is the name of your first pet', 'what is the name of your first pet'), ('what is the name of your birth place', 'what is the name of your birth place'), ('what is the name of place where you live', 'what is the name of place where you live')], max_length=150)),
                ('security_question1_value', models.CharField(max_length=50)),
                ('security_question2', models.CharField(choices=[('what is the name of your first school', 'what is the name of your first pet'), ('what is the name of your friend', 'what is the name of your friend'), ('what is your favourite color', 'what is your favourite color')], max_length=150)),
                ('security_question2_value', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='User_Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'User_Reviews',
            },
        ),
    ]
